version: 0.2

env:
  variables:
    SOLUTION: .\HelloWorld.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.6.2

phases:
  build:
    commands:
      - '& "C:\ProgramData\chocolatey\bin\choco.exe" upgrade nuget.commandline'
      - '& "C:\ProgramData\chocolatey\bin\NuGet.exe" restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY'
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" /p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v$env:DOTNET_FRAMEWORK" $env:SOLUTION /p:DeployOnBuild=true /p:PublishProfile=HelloWorld.pubxml'  
artifacts:
  files:
    - .\HelloWorld\Deploy\**\*
    - .\appspec.yml
